/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccountPasswords: () => import('#controllers/account_passwords_controller'),
  AccountRegistrations: () => import('#controllers/account_registrations_controller'),
  Accounts: () => import('#controllers/accounts_controller'),
  ActiveSchools: () => import('#controllers/active_schools_controller'),
  ActivityBankActivities: () => import('#controllers/activity_bank_activities_controller'),
  ActivityBankCategories: () => import('#controllers/activity_bank_categories_controller'),
  BankPacks: () => import('#controllers/bank_packs_controller'),
  ClassLessons: () => import('#controllers/class_lessons_controller'),
  CustomerPlans: () => import('#controllers/customer_plans_controller'),
  CustomerPurchases: () => import('#controllers/customer_purchases_controller'),
  Enrolments: () => import('#controllers/enrolments_controller'),
  Home: () => import('#controllers/home_controller'),
  Invitations: () => import('#controllers/invitations_controller'),
  Learners: () => import('#controllers/learners_controller'),
  LessonSchedules: () => import('#controllers/lesson_schedules_controller'),
  LevelSettings: () => import('#controllers/level_settings_controller'),
  Levels: () => import('#controllers/levels_controller'),
  Members: () => import('#controllers/members_controller'),
  Memberships: () => import('#controllers/memberships_controller'),
  PaystackWebhooks: () => import('#controllers/paystack_webhooks_controller'),
  Programs: () => import('#controllers/programs_controller'),
  SchoolAgeGroups: () => import('#controllers/school_age_groups_controller'),
  Schools: () => import('#controllers/schools_controller'),
  Sessions: () => import('#controllers/sessions_controller'),
  SignInLinks: () => import('#controllers/sign_in_links_controller'),
  Signups: () => import('#controllers/signups_controller'),
  SkillBankFamilies: () => import('#controllers/skill_bank_families_controller'),
  SkillBankSkills: () => import('#controllers/skill_bank_skills_controller'),
  SwimYears: () => import('#controllers/swim_years_controller'),
  SwimmingClasses: () => import('#controllers/swimming_classes_controller'),
}
