/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Accounts: () => import('#controllers/accounts_controller'),
  Sessions: () => import('#controllers/sessions_controller'),
  SignInLinks: () => import('#controllers/sign_in_links_controller'),
}
