/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class ClassStageSkillSchema extends BaseModel {
  static $columns = ['classStageId', 'createdAt', 'id', 'skillId', 'updatedAt'] as const
  $columns = ClassStageSkillSchema.$columns
  @column()
  declare classStageId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare skillId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ClassStageSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'position', 'swimmingClassId', 'updatedAt'] as const
  $columns = ClassStageSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare position: number
  @column()
  declare swimmingClassId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class InvitationSchema extends BaseModel {
  static $columns = ['acceptedAt', 'createdAt', 'email', 'expiresAt', 'id', 'inviteeName', 'inviteePhone', 'roleId', 'schoolId', 'token', 'updatedAt'] as const
  $columns = InvitationSchema.$columns
  @column.dateTime()
  declare acceptedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare inviteeName: string | null
  @column()
  declare inviteePhone: string | null
  @column()
  declare roleId: number
  @column()
  declare schoolId: number
  @column()
  declare token: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LearnerSchema extends BaseModel {
  static $columns = ['createdAt', 'dateOfBirth', 'firstName', 'gender', 'id', 'lastName', 'medicalInfo', 'nationality', 'residentialLocation', 'signupId', 'swimmingExperience', 'updatedAt'] as const
  $columns = LearnerSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare dateOfBirth: DateTime
  @column()
  declare firstName: string
  @column()
  declare gender: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lastName: string
  @column()
  declare medicalInfo: string
  @column()
  declare nationality: string
  @column()
  declare residentialLocation: string
  @column()
  declare signupId: number
  @column()
  declare swimmingExperience: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LevelStageActivitySchema extends BaseModel {
  static $columns = ['createdAt', 'durationMinutes', 'id', 'levelStageId', 'name', 'updatedAt'] as const
  $columns = LevelStageActivitySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare durationMinutes: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare levelStageId: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LevelStageSkillSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'levelStageId', 'name', 'passCriteria', 'updatedAt'] as const
  $columns = LevelStageSkillSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare levelStageId: number
  @column()
  declare name: string
  @column()
  declare passCriteria: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LevelStageSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'levelId', 'name', 'position', 'updatedAt'] as const
  $columns = LevelStageSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare levelId: number
  @column()
  declare name: string
  @column()
  declare position: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LevelSchema extends BaseModel {
  static $columns = ['ageGroup', 'capacity', 'createdAt', 'defaultFee', 'description', 'id', 'name', 'programId', 'updatedAt'] as const
  $columns = LevelSchema.$columns
  @column()
  declare ageGroup: string
  @column()
  declare capacity: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare defaultFee: number
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare programId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MembershipRoleSchema extends BaseModel {
  static $columns = ['id', 'membershipId', 'roleId'] as const
  $columns = MembershipRoleSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare membershipId: number
  @column()
  declare roleId: number
}

export class MembershipSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'schoolId', 'updatedAt', 'userId'] as const
  $columns = MembershipSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare schoolId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class OrganisationSchema extends BaseModel {
  static $columns = ['createdAt', 'createdByUserId', 'id', 'isPremium', 'name', 'slug', 'updatedAt'] as const
  $columns = OrganisationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdByUserId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isPremium: boolean
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProgramSchema extends BaseModel {
  static $columns = ['activatedAt', 'createdAt', 'description', 'id', 'name', 'updatedAt'] as const
  $columns = ProgramSchema.$columns
  @column.dateTime()
  declare activatedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RoleSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'permissions', 'updatedAt'] as const
  $columns = RoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare permissions: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SchoolLevelSettingSchema extends BaseModel {
  static $columns = ['available', 'createdAt', 'fee', 'id', 'levelId', 'schoolId', 'updatedAt'] as const
  $columns = SchoolLevelSettingSchema.$columns
  @column()
  declare available: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare fee: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare levelId: number
  @column()
  declare schoolId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SchoolSchema extends BaseModel {
  static $columns = ['createdAt', 'createdByUserId', 'id', 'location', 'name', 'organisationId', 'slug', 'updatedAt'] as const
  $columns = SchoolSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdByUserId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare location: string
  @column()
  declare name: string
  @column()
  declare organisationId: number
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SignupSchema extends BaseModel {
  static $columns = ['contactEmail', 'contactName', 'contactPhone', 'createdAt', 'id', 'message', 'schoolId', 'updatedAt', 'whatsapp'] as const
  $columns = SignupSchema.$columns
  @column()
  declare contactEmail: string
  @column()
  declare contactName: string
  @column()
  declare contactPhone: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare message: string | null
  @column()
  declare schoolId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare whatsapp: string | null
}

export class SkillSchema extends BaseModel {
  static $columns = ['createdAt', 'createdByUserId', 'description', 'id', 'isDefault', 'name', 'schoolId', 'updatedAt'] as const
  $columns = SkillSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdByUserId: number | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isDefault: boolean
  @column()
  declare name: string
  @column()
  declare schoolId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SwimmingClassSessionSchema extends BaseModel {
  static $columns = ['cancelledAt', 'createdAt', 'endsAt', 'id', 'startsAt', 'swimmingClassId', 'updatedAt'] as const
  $columns = SwimmingClassSessionSchema.$columns
  @column.dateTime()
  declare cancelledAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare endsAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare startsAt: DateTime
  @column()
  declare swimmingClassId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SwimmingClassWeekdaySchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'swimmingClassId', 'updatedAt', 'weekday'] as const
  $columns = SwimmingClassWeekdaySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare swimmingClassId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare weekday: number
}

export class SwimmingClassSchema extends BaseModel {
  static $columns = ['cancelledAt', 'capacity', 'code', 'createdAt', 'endDate', 'endTime', 'id', 'instructorMembershipId', 'levelId', 'location', 'name', 'pendingInstructorInvitationId', 'schoolId', 'startDate', 'startTime', 'updatedAt'] as const
  $columns = SwimmingClassSchema.$columns
  @column.dateTime()
  declare cancelledAt: DateTime | null
  @column()
  declare capacity: number
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare endDate: DateTime
  @column()
  declare endTime: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare instructorMembershipId: number | null
  @column()
  declare levelId: number
  @column()
  declare location: string
  @column()
  declare name: string
  @column()
  declare pendingInstructorInvitationId: number | null
  @column()
  declare schoolId: number
  @column.date()
  declare startDate: DateTime
  @column()
  declare startTime: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['activeOrganisationId', 'activeSchoolId', 'country', 'createdAt', 'email', 'fullName', 'id', 'phone', 'profileCompletedAt', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare activeOrganisationId: number | null
  @column()
  declare activeSchoolId: number | null
  @column()
  declare country: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare phone: string | null
  @column.dateTime()
  declare profileCompletedAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
