/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class ClubSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'createdByUserId',
    'id',
    'location',
    'name',
    'slug',
    'updatedAt',
  ] as const
  $columns = ClubSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdByUserId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare location: string
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class InvitationSchema extends BaseModel {
  static $columns = [
    'acceptedAt',
    'clubId',
    'createdAt',
    'email',
    'expiresAt',
    'id',
    'roleId',
    'token',
    'updatedAt',
  ] as const
  $columns = InvitationSchema.$columns
  @column.dateTime()
  declare acceptedAt: DateTime | null
  @column()
  declare clubId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare roleId: number
  @column()
  declare token: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LearnerSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'dateOfBirth',
    'gender',
    'id',
    'medicalInfo',
    'name',
    'nationality',
    'residentialLocation',
    'signupId',
    'swimmingExperience',
    'updatedAt',
  ] as const
  $columns = LearnerSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare dateOfBirth: DateTime
  @column()
  declare gender: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare medicalInfo: string
  @column()
  declare name: string
  @column()
  declare nationality: string
  @column()
  declare residentialLocation: string
  @column()
  declare signupId: number
  @column()
  declare swimmingExperience: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MembershipRoleSchema extends BaseModel {
  static $columns = ['id', 'membershipId', 'roleId'] as const
  $columns = MembershipRoleSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare membershipId: number
  @column()
  declare roleId: number
}

export class MembershipSchema extends BaseModel {
  static $columns = ['clubId', 'createdAt', 'id', 'updatedAt', 'userId'] as const
  $columns = MembershipSchema.$columns
  @column()
  declare clubId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class RoleSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'permissions', 'updatedAt'] as const
  $columns = RoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare permissions: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SignupSchema extends BaseModel {
  static $columns = [
    'clubId',
    'contactEmail',
    'contactName',
    'contactPhone',
    'createdAt',
    'id',
    'message',
    'updatedAt',
    'whatsapp',
  ] as const
  $columns = SignupSchema.$columns
  @column()
  declare clubId: number
  @column()
  declare contactEmail: string
  @column()
  declare contactName: string
  @column()
  declare contactPhone: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare message: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare whatsapp: string | null
}

export class UserSchema extends BaseModel {
  static $columns = [
    'activeClubId',
    'country',
    'createdAt',
    'email',
    'fullName',
    'id',
    'phone',
    'profileCompletedAt',
    'updatedAt',
  ] as const
  $columns = UserSchema.$columns
  @column()
  declare activeClubId: number | null
  @column()
  declare country: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare phone: string | null
  @column.dateTime()
  declare profileCompletedAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
