/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type { InferSharedProps } from '@adonisjs/inertia/types'
import type AccountTransformer from '#transformers/account_transformer'
import type LearnerTransformer from '#transformers/learner_transformer'
import type LevelTransformer from '#transformers/level_transformer'
import type MembershipTransformer from '#transformers/membership_transformer'
import type OrganisationTransformer from '#transformers/organisation_transformer'
import type ProgramTransformer from '#transformers/program_transformer'
import type SchoolTransformer from '#transformers/school_transformer'
import type SignupTransformer from '#transformers/signup_transformer'
import type SwimYearTransformer from '#transformers/swim_year_transformer'
import type SwimmingClassTransformer from '#transformers/swimming_class_transformer'
import type UserTransformer from '#transformers/user_transformer'
import type InertiaMiddleware from '#middleware/inertia_middleware'

export namespace Data {
  export type Account = InferData<AccountTransformer>
  export namespace Account {
    export type Variants = InferVariants<AccountTransformer>
  }
  export type Learner = InferData<LearnerTransformer>
  export namespace Learner {
    export type Variants = InferVariants<LearnerTransformer>
  }
  export type Level = InferData<LevelTransformer>
  export namespace Level {
    export type Variants = InferVariants<LevelTransformer>
  }
  export type Membership = InferData<MembershipTransformer>
  export namespace Membership {
    export type Variants = InferVariants<MembershipTransformer>
  }
  export type Organisation = InferData<OrganisationTransformer>
  export namespace Organisation {
    export type Variants = InferVariants<OrganisationTransformer>
  }
  export type Program = InferData<ProgramTransformer>
  export namespace Program {
    export type Variants = InferVariants<ProgramTransformer>
  }
  export type School = InferData<SchoolTransformer>
  export namespace School {
    export type Variants = InferVariants<SchoolTransformer>
  }
  export type Signup = InferData<SignupTransformer>
  export namespace Signup {
    export type Variants = InferVariants<SignupTransformer>
  }
  export type SwimYear = InferData<SwimYearTransformer>
  export namespace SwimYear {
    export type Variants = InferVariants<SwimYearTransformer>
  }
  export type SwimmingClass = InferData<SwimmingClassTransformer>
  export namespace SwimmingClass {
    export type Variants = InferVariants<SwimmingClassTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
  export type SharedProps = InferSharedProps<InertiaMiddleware>
}
