/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export type { PermissionKey } from '#start/permissions'

export type { Permission as PermissionEntry } from '@adonisplus/permissions/types'

